[project]
name = "dynamicpipe"
description = "Pack and unpack any number of typed values through a dynamic pipe in ComfyUI."
version = "2.0.0"
license = { text = "MIT License" }
dependencies = []
classifiers = [
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/palealloy2999-prog/ComfyUI-DynamicPipe"
Documentation = "https://github.com/palealloy2999-prog/ComfyUI-DynamicPipe"
"Bug Tracker" = "https://github.com/palealloy2999-prog/ComfyUI-DynamicPipe/issues"

[tool.comfy]
PublisherId = "palealloy"
DisplayName = "ComfyUI-DynamicPipe"
Icon = "https://avatars.githubusercontent.com/u/230474078?s=400&v=4"
